# Generated by Django 2.0.3 on 2018-04-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
