# Generated by Django 2.0.4 on 2018-05-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
