# Generated by Django 2.0.4 on 2018-05-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_quote_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_text',
            field=models.CharField(max_length=600, unique=True),
        ),
    ]
